export const onboarding = {
  businessRoles: [
    { value: "manufacturer", label: "Manufacturer" },
    { value: "trader", label: "Trader" },
    { value: "distributor", label: "Distributor" },
    { value: "wholesaler", label: "Wholesaler" },
    { value: "retailer", label: "Retailer" },
    { value: "broker", label: "Broker" },
    { value: "commission-agent", label: "Commission Agent" },
    { value: "consultant", label: "Consultant" },
    { value: "exporter", label: "Exporter" },
    { value: "importer", label: "Importer" },
    { value: "oem", label: "Original Equipment Manufacturer" },
    { value: "ogm", label: "Original Design Manufacturer" },
    { value: "service-provider", label: "Service Provider" },
    { value: "startup", label: "Startup" },
    { value: "sourcing-agent", label: "Sourcing Agent" },
    { value: "aggregator", label: "Aggregator" },
    { value: "freelancer", label: "Freelance Service Provider" },
  ],

  legalStatuses: [
    { value: "sole_prop", label: "Sole Proprietorship"},
    { value: "partnership", label: "Partnership"},
    { value: "private_lc", label: "Private Limited Company"},
    { value: "public_lc", label: "Public Limited Company"},
    { value: "llc", label: "LLC"},
    { value: "non_profit", label: "Non Profit / NGO"},
    { value: "individual", label: "Freelancer / Individual"},
  ],

  companySizes: [
    { value: "individual", Label: "Individual"},
    { value: "small", Label: "Small"},
    { value: "medium", Label: "Medium"},
    { value: "national", Label: "National"},
    { value: "multi_national", Label: "Multi-National"},

  ],

  businessCategories: [
    {
      value: "technology",
      label: "Technology",
      subcategories: [
        { value: "software-products", label: "Software Products" },
        { value: "it-services", label: "IT Services" },
        { value: "cloud-computing", label: "Cloud Computing" },
        { value: "cybersecurity", label: "Cybersecurity" },
        { value: "ai-ml", label: "Artificial Intelligence / Machine Learning" },
        { value: "hardware", label: "Computer Hardware" },
        { value: "consumer-electronics", label: "Consumer Electronics" },
        { value: "iot", label: "Internet of Things (IoT)" },
        { value: "gaming", label: "Gaming & Entertainment Tech" },
      ],
    },
    {
      value: "healthcare",
      label: "Healthcare",
      subcategories: [
        { value: "medical-devices", label: "Medical Devices" },
        { value: "pharmaceuticals", label: "Pharmaceuticals" },
        { value: "hospital-services", label: "Hospital & Clinical Services" },
        { value: "telemedicine", label: "Telemedicine" },
        { value: "healthcare-it", label: "Healthcare IT Solutions" },
        { value: "wellness-products", label: "Wellness & Fitness Products" },
        { value: "lab-services", label: "Laboratory Services" },
      ],
    },
    {
      value: "manufacturing",
      label: "Manufacturing",
      subcategories: [
        { value: "automotive-parts", label: "Automotive Parts & Components" },
        { value: "machinery", label: "Industrial Machinery" },
        { value: "construction-materials", label: "Construction Materials" },
        { value: "metals", label: "Metals & Fabrication" },
        { value: "plastics", label: "Plastics & Polymers" },
        { value: "chemicals", label: "Chemicals & Raw Materials" },
        { value: "electronics-manufacturing", label: "Electronics Manufacturing" },
      ],
    },
    {
      value: "agriculture",
      label: "Agriculture & Food",
      subcategories: [
        { value: "crops", label: "Crops & Farming" },
        { value: "dairy", label: "Dairy Products" },
        { value: "meat", label: "Meat & Poultry" },
        { value: "seafood", label: "Seafood" },
        { value: "agrochemicals", label: "Agrochemicals" },
        { value: "farm-equipment", label: "Farm Equipment & Machinery" },
        { value: "packaged-food", label: "Packaged & Processed Food" },
        { value: "beverages", label: "Beverages" },
      ],
    },
    {
      value: "fashion",
      label: "Fashion & Apparel",
      subcategories: [
        { value: "clothing", label: "Clothing" },
        { value: "footwear", label: "Footwear" },
        { value: "accessories", label: "Accessories" },
        { value: "textiles", label: "Textiles & Fabrics" },
        { value: "luxury", label: "Luxury Goods" },
        { value: "sportswear", label: "Sportswear" },
      ],
    },
    {
      value: "energy",
      label: "Energy & Environment",
      subcategories: [
        { value: "renewable-energy", label: "Renewable Energy" },
        { value: "oil-gas", label: "Oil & Gas" },
        { value: "mining", label: "Mining & Minerals" },
        { value: "environmental-services", label: "Environmental Services" },
        { value: "energy-storage", label: "Energy Storage & Batteries" },
      ],
    },
    {
      value: "construction",
      label: "Construction & Real Estate",
      subcategories: [
        { value: "residential", label: "Residential Construction" },
        { value: "commercial", label: "Commercial Construction" },
        { value: "infrastructure", label: "Infrastructure Projects" },
        { value: "real-estate", label: "Real Estate Development" },
        { value: "interior-design", label: "Interior Design" },
      ],
    },
    {
      value: "logistics",
      label: "Logistics & Transportation",
      subcategories: [
        { value: "freight-forwarding", label: "Freight Forwarding" },
        { value: "warehousing", label: "Warehousing" },
        { value: "courier-services", label: "Courier & Parcel Services" },
        { value: "shipping", label: "Shipping Lines" },
        { value: "public-transport", label: "Public Transport" },
        { value: "vehicle-rental", label: "Vehicle Rental Services" },
      ],
    },
    {
      value: "education",
      label: "Education & Training",
      subcategories: [
        { value: "schools", label: "Schools & Colleges" },
        { value: "e-learning", label: "E-Learning Platforms" },
        { value: "corporate-training", label: "Corporate Training" },
        { value: "vocational", label: "Vocational Education" },
        { value: "edtech", label: "EdTech Products" },
      ],
    },
    {
      value: "hospitality",
      label: "Hospitality & Tourism",
      subcategories: [
        { value: "hotels", label: "Hotels & Resorts" },
        { value: "restaurants", label: "Restaurants & Cafes" },
        { value: "travel-agencies", label: "Travel Agencies" },
        { value: "tour-operators", label: "Tour Operators" },
        { value: "event-management", label: "Event Management" },
      ],
    },
  ],

  businessModels: [
    { value: "b2b", label: "B2B"},
    { value: "b2c", label: "B2C"},
    { value: "c2c", label: "C2C"},
    { value: "d2c", label: "D2C"},
    { value: "franchise_reseller", label: "Franchise / Reseller"},
    { value: "sub_based", label: "Subscription-Based"},
    { value: "service_based", label: "Service Based"},
  ]
};